---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'mytheme'
PDFExtension:
  wkhtmltopdf_binary: 'D:/Apache24/htdocs/demosite/vendor/bin/wkhtmltopdf'
MovieListPage:
  extensions:
    - PDFExtension

Director:
  environment_type: 'dev'